import 'item_model.dart';

final List<ItemModel> allItems = [
  // --- Endings ---
  ItemModel(
    id: 'the_dark_soul',
    title: "The Dark Soul",
    imagePath: "assets/achievements/the_dark_soul.png",
    subItems: ["Complete all achievements."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'to_link_the_first_flame',
    title: "To Link the First Flame",
    imagePath: "assets/achievements/to_link_the_first_flame.png",
    subItems: ["Reach \"To Link the First Flame\" ending."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'the_end_of_fire',
    title: "The End of Fire",
    imagePath: "assets/achievements/the_end_of_fire.png",
    subItems: ["Reach \"The End of Fire\" ending."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'the_usurpation_of_fire',
    title: "The Usurpation of Fire",
    imagePath: "assets/achievements/the_usurpation_of_fire.png",
    subItems: ["Reach \"The Usurpation of Fire\" ending."],
    isChecked: false,
    subItemsChecked: [false],
  ),

  // --- Boss / Story / Progress ---
  ItemModel(
    id: 'iudex_gundyr',
    title: "Iudex Gundyr",
    imagePath: "assets/achievements/iudex_gundry_trophy.png",
    subItems: ["Defeat Iudex Gundyr."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'vordt_of_the_boreal_valley',
    title: "Vordt of the Boreal Valley",
    imagePath: "assets/achievements/vordt_of_the_boreal_valley_trophy.png",
    subItems: ["Defeat Vordt of the Boreal Valley."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'curse_rotted_greatwood',
    title: "Curse-rotted Greatwood",
    imagePath: "assets/achievements/curse-rotted_greatwood_trophy.png",
    subItems: ["Defeat Curse-rotted Greatwood."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'crystal_sage',
    title: "Crystal Sage",
    imagePath: "assets/achievements/crystal_sage_trophy.png",
    subItems: ["Defeat Crystal Sage."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'deacons_of_the_deep',
    title: "Deacons of the Deep",
    imagePath: "assets/achievements/deacons_of_the_deep_trophy.png",
    subItems: ["Defeat Deacons of the Deep."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'abyss_watchers',
    title: "Abyss Watchers",
    imagePath: "assets/achievements/curse-rotted_greatwood_trophy.png",
    subItems: ["Defeat Abyss Watchers, Lords of Cinder."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'high_lord_wolnir',
    title: "High Lord Wolnir",
    imagePath: "assets/achievements/high_lord_wolnir_trophy.png",
    subItems: ["Defeat High Lord Wolnir."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'pontiff_sulyvahn',
    title: "Pontiff Sulyvahn",
    imagePath: "assets/achievements/pontiff_sulyvahn_trophy.png",
    subItems: ["Defeat Pontiff Sulyvahn."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'yhorm_the_giant',
    title: "Yhorm the Giant",
    imagePath: "assets/achievements/lord_of_cinder_yhorm_the_giant.png",
    subItems: ["Defeat Yhorm the Giant."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'aldrich_devourer_of_gods',
    title: "Aldrich, Devourer of Gods",
    imagePath:
        "assets/achievements/lord_of_cinder_aldritch_devourer_of_gods.png",
    subItems: ["Defeat Aldrich, Devourer of Gods."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'lothric_younger_prince',
    title: "Lothric, Younger Prince",
    imagePath:
        "assets/achievements/lord_of_cinder_lothric_younger_prince.png",
    subItems: ["Defeat Lothric & Lorian (Twin Princes)."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'dragonslayer_armour',
    title: "Dragonslayer Armour",
    imagePath: "assets/achievements/dragonslayer_armour_trophy.png",
    subItems: ["Defeat Dragonslayer Armour."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'oceiros_the_consumed_king',
    title: "Oceiros, the Consumed King",
    imagePath: "assets/achievements/oceiros_the_consumed_king_trophy.png",
    subItems: ["Defeat Oceiros, the Consumed King."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'champion_gundyr',
    title: "Champion Gundyr",
    imagePath: "assets/achievements/champion_gundyr_trophy.png",
    subItems: ["Defeat Champion Gundyr."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'ancient_wyvern',
    title: "Ancient Wyvern",
    imagePath: "assets/achievements/ancient_wyvern_trophy.png",
    subItems: [
      "Perform the plunging attack from the ledge at Archdragon Peak."
    ],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'the_nameless_king',
    title: "The Nameless King",
    imagePath: "assets/achievements/the_nameless_king_trophy.png",
    subItems: ["Defeat Nameless King."],
    isChecked: false,
    subItemsChecked: [false],
  ),

  // --- Exploration ---
  ItemModel(
    id: 'archdragon_peak',
    title: "Archdragon Peak",
    imagePath: "assets/achievements/archdragon_peak.png",
    subItems: ["Reach Archdragon Peak."],
    isChecked: false,
    subItemsChecked: [false],
  ),
  ItemModel(
    id: 'untended_graves',
    title: "Untended Graves",
    imagePath: "assets/achievements/untended_graves.png",
    subItems: ["Reach Untended Graves."],
    isChecked: false,
    subItemsChecked: [false],
  ),
];
