// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GfS5Y9klKWDa1YFmK0hm4FQ6bkXd-2k',
    appId: '1:305558633894:web:bdaefef9d5a981a5c8a367',
    messagingSenderId: '305558633894',
    projectId: 'flutterfulllearn',
    authDomain: 'flutterfulllearn.firebaseapp.com',
    storageBucket: 'flutterfulllearn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwSM-i-FyAipEnOwdHrPaWYXG1lLHyjY',
    appId: '1:305558633894:android:e01b5a80bfb7a90ac8a367',
    messagingSenderId: '305558633894',
    projectId: 'flutterfulllearn',
    storageBucket: 'flutterfulllearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3_a10rROxqwm5p66CHd9F9jXTaHxGb8',
    appId: '1:305558633894:ios:4d94be6d7001d328c8a367',
    messagingSenderId: '305558633894',
    projectId: 'flutterfulllearn',
    storageBucket: 'flutterfulllearn.firebasestorage.app',
    iosClientId: '305558633894-lvojdq8bgf6pfc9ank13d5mqhva0g491.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFullLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ3_a10rROxqwm5p66CHd9F9jXTaHxGb8',
    appId: '1:305558633894:ios:4d94be6d7001d328c8a367',
    messagingSenderId: '305558633894',
    projectId: 'flutterfulllearn',
    storageBucket: 'flutterfulllearn.firebasestorage.app',
    iosClientId: '305558633894-lvojdq8bgf6pfc9ank13d5mqhva0g491.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFullLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0GfS5Y9klKWDa1YFmK0hm4FQ6bkXd-2k',
    appId: '1:305558633894:web:f176dcb14d0281a6c8a367',
    messagingSenderId: '305558633894',
    projectId: 'flutterfulllearn',
    authDomain: 'flutterfulllearn.firebaseapp.com',
    storageBucket: 'flutterfulllearn.firebasestorage.app',
  );
}
